module.exports = {
  RECEIVE_USER: 'RECEIVE_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  RECEIVE_IMAGE: 'RECEIVE_IMAGE',
  RECEIVE_CACHED_USER: 'RECEIVE_CACHED_USER'
};
