module.exports = {
  GET_CONNECTION: 'GET_CONNECTION',
  GET_CONNECTION_CACHE: 'GET_CONNECTION_CACHE',
  CREATE_CONNECTION: 'CREATE_CONNECTION',
  UPDATE_CONNECTION: 'UPDATE_CONNECTION',
  DELETE_CONNECTION: 'DELETE_CONNECTION'
};
