language: node_js
services:
  - xvfb
node_js:
  - lts/*
cache: yarn

jobs:
  include:
    - stage: Test
      script:
        - yarn
        - yarn test

stages:
  - name: Test
    if: type = push OR type = pull_request

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL