language: node_js
services:
  - xvfb
node_js:
  - lts/*
cache: yarn

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/677961620269432875/2gU1M7sdOG9d671T2YUWJNkBxB0UEWRT7DP8dKitrtzKD9Tr0L-wTeEziKczjJCX5NWr
    on_start: never
    on_cancel: never

jobs:
  include:
    - stage: Test
      script:
        - yarn
        - yarn test

stages:
  - name: Test
    if: type = push OR type = pull_request
