export const IPC = {
  SET_CACHE: 'SET_CACHE',
  SET_CONFIG: 'SET_CONFIG',
  SET_THEME: 'SET_THEME'
};

export const AUDIO = {
  SET_METADATA: 'SET_METADATA',
  SET_PLAYER: 'SET_PLAYER',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_VOLUME: 'SET_VOLUME',
  SET_POSITION: 'SET_POSITION',
  SET_STATUS: 'SET_STATUS'
};
