const TYPES_IPC = {
  KEYBOARD: 'KEYBOARD'
};

const COMMANDS_AUDIO = {
  NEXT: 'NEXT',
  PREVIOUS: 'PREVIOUS',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  VOLUME_UP: 'VOLUME_UP',
  VOLUME_DOWN: 'VOLUME_DOWN',
  MUTE: 'MUTE'
};

module.exports = {
  TYPES_IPC,
  COMMANDS_AUDIO
};
