export const SELECT_PATH_DIALOG = 'SELECT_PATH_DIALOG';
export const SELECT_BACKGROUND_DIALOG = 'SELECT_BACKGROUND_DIALOG';
export const SET_BUSY = 'SET_BUSY';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const DELETE_DATABASE = 'DELETE_DATABASE';
export const SET_DATABASE_UPDATED = 'SET_DATABASE_UPDATED';
export const SEARCH_DATABASE = 'SEARCH_DATABASE';
export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
