export const SET_PLAYLIST = 'SET_PLAYLIST';
export const POP_PLAYLIST = 'POP_PLAYLIST';
export const SET_PLAYLIST_INDEX = 'SET_PLAYLIST_INDEX';
export const SHUFFLE_PLAYLIST = 'SHUFFLE_PLAYLIST';
export const PUSH_PLAYLIST = 'PUSH_PLAYLIST';
export const SET_CUSTOM_PLAYLIST = 'SET_CUSTOM_PLAYLIST';
