name: ci
on: [push, pull_request]
jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.3
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm run test
      - name: Discord Webhook (Success)
        if: ${{success()}}
        run: |
          wget https://raw.githubusercontent.com/chronoDave/user-scripts/master/webhooks/github_discord.js
          node ./github_discord.js ${{secrets.WEBHOOK_URL}} success
      - name: Discord Webhook (Failure)
        if: ${{failure()}}
        run: |
          wget https://raw.githubusercontent.com/chronoDave/user-scripts/master/webhooks/github_discord.js
          node ./github_discord.js ${{secrets.WEBHOOK_URL}} error